### PR TITLE
Windows colors support (cmd & PowerShell) + extra options

### PR DESCRIPTION
**Pull request by brutestack**
1) Adds Windows console colors support for Command Prompt and PowerShell
2) Adds option to output format string instead of image. Output then can be used in Printf function to print image in users application.
3) Adds option to disable setting backgrounds for cahracters

### CODE REVIEW

**Comment by eliukblau** [comment]
Hi. Thanks for contributing 👍 Can you explain with more detail the 3 points that you added? What produced it and why is the change necessary? What is the change, specifically? :)

**Comment by brutestack** [comment]
1. Windows console colors support (Command Prompt & PowerShell)
I tried pixterm on Windows 10 and discovered that it is not working correctly: colors are wrong and resulting image is not readable.
The problem source is that Windows console (both Command prompt and PowerShell) by default has vt100 escape sequences disabled.
To enable it process needs to call WinAPI function SetConsoleMode passing STDOUT handle and ENABLE_VIRTUAL_TERMINAL_PROCESSING flag.
https://docs.microsoft.com/en-us/windows/console/setconsolemode
That is exactly what my new function ansimage.EnableColorsInTerminal() does on Windows. On other OSs it does nothing.
I'm calling it just after pixterm parses its arguments because you also need it for ansimage.ClearTerminal() to work properly on Windows.

2. Option to output format string instead of image. Output then can be used in Printf function to print image in users application.
I wanted to add ASCII logo to my project (https://brute.network/) and was really impressed by pixterm display quality and style. However there where no way to save resulting color ASCII output of pixterm for later use in my console app just by printing some string.
That is why I have added -code argument flag. It makes pixterm to output format string instead of color art. Resulting format string can be used as is in any Printf-like function to display color ASCII art in your own console app.
Simple usage example:
	a. In console: `pixterm -d 2 -tc 80 -tr 19 -code image.png >output.txt`
	(Note -code argument)
	b. copy the contents of output.txt file to clipboard
	c. in your code: `fmt.Printf("<...paste here...>")`

3. Option to disable setting backgrounds for cahracters.
Pixterm sets backgrounds for characters using vt100 escape codes. But often, when you need to create logo for your console app, you don't need it to change terminal default background color. That is why I have added -trans argument flag to inform pixterm not to set background color on characters.
Here is the example (note the difference when -trans flag appears):
	`pixterm -d 2 -tc 80 -tr 19 wallpaper-fs.png`
bg

	`pixterm -d 2 -tc 80 -tr 19 -trans wallpaper-fs.png`
trans

**Comment by eliukblau** [comment]
Thanks for the reply. I will review this PR. Please, give me some time :)

**Comment by eliukblau** [comment]
I will review the code soon. Thank you! and please be patient while I test all. :)

**Comment by eliukblau** [comment]
Solved in [v1.3.0](https://github.com/eliukblau/pixterm/releases/tag/v1.3.0)
@brutestack check your name in `-credits` option 😉
Thank you VERY MUCH for contributing with all of this interesting ideas 💖

**Comment by eliukblau** [comment]
@brutestack 
Oh, can you check if Windows patch works fine? :)

**Comment by brutestack** [comment]
Everything is fine. I checked both Widnows Command prompt and PowerShell :thumbsup:
Thanks for credits and for your great 5:star: tool

**Pull request merged**
