### PR TITLE
Added go.mod support

### PR DESCRIPTION
**Pull request by diamondburned**

### CODE REVIEW

**Comment by eliukblau** [comment]
Thank you. I will leave this PR on standby, while the support of Go Modules is not yet official. Only from upcomming version 1.13, modules become official. We will wait until then.

[Go Modules in 2019](https://blog.golang.org/modules2019#TOC_2.)

**Comment by mattn** [comment]
I feed this is good to merge. Thought?

**Comment by mattn** [comment]
Current implementation have a problem that can't build with latest go-colorful. And most users using go1.13 faice this issue.

**Comment by eliukblau** [comment]
Yeah, it is in the making. I have had little time for this. Thank you for your interest :)

It will be published officially along with a couple of new patches and functionalities from contributors. Give me time ;)

**Comment by MichaelMure** [comment]
I can confirm that it would help, now that go1.13 is here. Also, current code use go-colorful v0.9, so not the version used in this PR.

**Comment by mattn** [comment]
Why don't you merge this?

**Comment by eliukblau** [comment]
https://github.com/eliukblau/pixterm/pull/12#issuecomment-541458346

https://github.com/eliukblau/pixterm/issues/11#issuecomment-487462178

https://github.com/eliukblau/pixterm/pull/8

**Comment by eliukblau** [comment]
Solved in [v1.3.0](https://github.com/eliukblau/pixterm/releases/tag/v1.3.0)

Thanks @diamondburned, @mattn, @MichaelMure for the comments about this and your interest 👍

**Pull request closed without merging**
